services: 
  db: 
    image: postgres:16.3
    container_name: booking_db
    env_file:
      - .env-not-dev
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7
    container_name: booking_redis
    env_file:
      - .env-not-dev

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    command: ['/booking/docker/app.sh']
    ports:
      - "7777:8000"
    env_file:
      - .env-not-dev
    depends_on:
      - db
      - redis

volumes:
  postgresdata: